### ISSUE TITLE
Module build failed: Error: File Loader

### ISSUE THREAD

**Issue by liliuchen** [webpack-contrib/url-loader#162]
version:1.1.2
Module build failed: Error: File Loader

emitFile is required from module system
    at Object.loader (xxx\web\node_modules\file-loader\dist\index.js:31:29)
    at Object.loader (xxx\web\node_modules\url-loader\dist\index.js:76:19)
 @ ./~/css-loader!./statics/css/site.css 7:301-344

**Comment by evilebottnawi** [comment]
@liliuchen can you create minimum reproducible test repo?

**Comment by andela-ooladayo** [comment]
@liliuchen I experienced the same issue. I had to rollback to version 1.0.1 before it worked with my file-loader.

Module build failed: Error: emitFile is required from module system
    at Object.module.exports (/usr/src/metrics-frontend/node_modules/file-loader/index.js:9:27)
    at Object.loader (/usr/src/metrics-frontend/node_modules/url-loader/dist/index.js:76:19)
 @ ./~/css-loader?sourceMap!./~/element-ui/lib/theme-chalk/index.css 6:860-896

**Comment by evilebottnawi** [comment]
@andela-ooladayo Please create minimum reproducible test repo

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!
