### ISSUE TITLE
Getting error ( options as Unexpected Identifier) 

### ISSUE THREAD

**Issue by RajeshKumar1990** [webpack-contrib/url-loader#84]
I am using url-loader to load image.
My react is 15.5.4,webpack is 3.3.0.
This is my webpack.config.js configuration
```
{

            test: /\.(png|jpg|gif)$/,
            use: [
              {
                loader: 'url-loader'
                options: {
                  limit: 8192
                }
              }]  
   }
```

Error is 

```
C:\Projects\React\websitenew\webpack.config.js:46
                options: {
                ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (C:\Projects\React\websitenew\node_modules\webpack\bin\convert-argv.js:97:18)
    at C:\Projects\React\websitenew\node_modules\webpack\bin\convert-argv.js:104:17

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! book@1.0.0 start: `webpack-dev-server --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the book@1.0.0 start script 'webpack-dev-server --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the book package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs book
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls book
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\React\websitenew\npm-debug.log

```
Is there any changes need to be made ????

**Comment by bebraw** [comment]
Instead of `loader: 'url-loader'` you should have `loader: 'url-loader',`. It's a syntax error.
